version: '3.9'

services:
  syncthing:
    image: syncthing/syncthing:1.23
    hostname: '{{.Node.Hostname}}'
    volumes:
      - /var/syncthing:/var/syncthing
    networks:
      - syncthing
    environment:
      - STGUIAPIKEY=A1B2C3
      #- STNODEFAULTFOLDER=1
    #ports:
    #  - target: 8384
    #    published: 48384
    #    protocol: tcp
    #    mode: host
    deploy:
      mode: global
      #placement:
      #  constraints:
      #    - node.labels.type==app

  syncthing-controller:
    image: node-sync:lts-alpine
    hostname: '{{.Node.Hostname}}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - syncthing
    environment:
      - STGUIAPIKEY=A1B2C3
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname==manager1
          # - node.role==manager

networks:
  syncthing:
    name: syncthing
    driver: overlay
    attachable: true
